# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wizE3Bpa-XFZWT-tZCkBanRTG5_xQHnd
"""

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset

root_path = '/content/sample_data/abc.csv'
dataset = pd.read_csv(root_path)

dataset

df = dataset.groupby(['State']).count()
df['Pharmacy Name']

import plotly.express as px
df = dataset.groupby(['State']).count()
fig = px.bar(dataset.groupby(['State'])['Pharmacy Name'].count())
fig.update_layout(title_text='State-wise Pharmacy count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)

fig

root_path2 = '/content/sample_data/Demography.csv'

dataset2 = pd.read_csv(root_path2)
dataset2

df2 = dataset2.groupby(['State']).mean()

import plotly.express as px
fig = px.bar(df2['Diabetes'])
fig.update_layout(title_text='State-wise Diabetes cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

import plotly.express as px

fig = px.bar(df2['Hypertension'])
fig.update_layout(title_text='State-wise Hypertension cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

import plotly.express as px

fig = px.bar(df2['CVD'])
fig.update_layout(title_text='State-wise CVD cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

import plotly.express as px

#fig = px.box(df['HIV/AIDS'])
fig = px.box(df2, y="HIV/AIDS")
fig.update_layout(title_text='State-wise HIV/AIDS cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

import plotly.express as px
# Number of males and females suffering from diabetes for given state
case = dataset2.groupby('State')['Diabetes'].sum()
case1 = dataset2.groupby('State')['MALES'].sum()
case2 = dataset2.groupby('State')['FEMALES'].sum()
case4 = (case/case1)*100.0
case4
case5 = (case/case2)*100.0
case5

case5 = ((case/case2)*100.0).round(2)
case5