# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wizE3Bpa-XFZWT-tZCkBanRTG5_xQHnd
"""

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset

root_path = '/content/sample_data/abc.csv'
dataset = pd.read_csv(root_path)

dataset

df = dataset.groupby(['State']).count()
df['Pharmacy Name']

import plotly.express as px
df = dataset.groupby(['State']).count()
fig = px.bar(dataset.groupby(['State'])['Pharmacy Name'].count())
fig.update_layout(title_text='State-wise Pharmacy count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)

fig

root_path2 = '/content/sample_data/Demography.csv'

dataset2 = pd.read_csv(root_path2)
dataset2

df2 = dataset2.groupby(['State']).mean()
df2

import plotly.express as px
fig = px.bar(df2['Diabetes'])
fig.update_layout(title_text='State-wise Diabetes cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

import plotly.express as px

fig = px.bar(df2['Hypertension'])
fig.update_layout(title_text='State-wise Hypertension cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

fig = px.bar(df2['CVD'])
fig.update_layout(title_text='State-wise CVD cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

#fig = px.box(df['HIV/AIDS'])
fig = px.bar(df2, y="HIV/AIDS")
fig.update_layout(title_text='State-wise HIV/AIDS cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

# Number of males and females suffering from diabetes for given state
case = dataset2.groupby('State')['Diabetes'].sum()
case1 = dataset2.groupby('State')['MALES'].sum()
case2 = dataset2.groupby('State')['FEMALES'].sum()
#male cases
case4 = (case1/case)
case4
#female cases
case5 = (case2/case)
case5.count()

y=[]
x = 0 
for i in range(52):
  y.append(0)
print(y)

fig = px.bar(case1, y="MALES")
fig.update_layout(title_text='State-wise HIV/AIDS cases count', title_x=0.5)
fig.write_html('first_figure.html', auto_open=True)
fig

main = []
for i in case5.reset_index()[0].values.tolist():
  if i <= 0:
    main.append(0)
  else: 
    main.append(i)

import numpy
explode= (0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
fig = px.pie(values=main, names=case5.reset_index()['State'].values.tolist())
fig.update_layout(title_text='Precentage of Females with Diabetes in each State')
fig.show()

main1 = []
for i in case4.reset_index()[0].values.tolist():
  if i <= 0:
    main1.append(0)
  else: 
    main1.append(i)

import plotly.graph_objects as go

# pull is given as a fraction of the pie radius
fig = go.Figure(data=[go.Pie(labels=case4.reset_index()['State'].values.tolist(), values=main1, pull=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])])
fig.update_layout(title_text='Precentage of Males with Diabetes in each State')
fig.show()

case5 = ((case/case2)*100.0).round(2)
case5

import plotly.express as px
# age 85 up suffering from diabetes,obesity,hiv, for given state
age85 = dataset2.groupby('State')['AGE_85_UP'].sum()

diabetic = (age85/(dataset2.groupby('State')['Diabetes'].sum()))*100
Prevalence_of_obesity = (age85/(dataset2.groupby('State')['Prevalence of obesity'].sum()))*100
hypertension = (age85/(dataset2.groupby('State')['Hypertension'].sum()))*100
CVD = (age85/(dataset2.groupby('State')['CVD'].sum()))*100
HIVAIDS = (age85/(dataset2.groupby('State')['HIV/AIDS'].sum()))*100
diabetic,Prevalence_of_obesity,hypertension,CVD,HIVAIDS

import pandas as pd
# import matplotlib library
import matplotlib.pyplot as plt

# age85 = dataset2.groupby('State')['AGE_85_UP'].sum()

# diabetic = (age85/(dataset2.groupby('State')['Diabetes'].sum()))*100
# Prevalence_of_obesity = (age85/(dataset2.groupby('State')['Prevalence of obesity'].sum()))*100
# hypertension = (age85/(dataset2.groupby('State')['Hypertension'].sum()))*100
# CVD = (age85/(dataset2.groupby('State')['CVD'].sum()))*100
# HIVAIDS = (age85/(dataset2.groupby('State')['HIV/AIDS'].sum()))*100
  
# plotting graph
#plt.figure(figsize=(55,15))
df2.reset_index().plot.bar(x="State", y=['AGE_75_84', 'Prevalence of obesity','Hypertension','CVD', 'MALES', 'FEMALES', ],width=1,figsize=(50,30)  )
#plt.figure(figsize=(cm_to_inch(50), cm_to_inch(25)))